### ISSUE TITLE
Sync/PullWordPairs doesn't work

### ISSUE THREAD

**Issue by prometium** [rugged-bl/InWords#30]
Sync/PullWordPairs doesn't work because web-api rolls out without any testing.

**Comment by Alword** [comment]
My bad. But this is caused by strange database behavior.
![image](https://user-images.githubusercontent.com/7733704/56289681-2c398a80-612a-11e9-9b6d-693251e98772.png)
I'll fix it.

**Comment by prometium** [comment]
thx
